services:

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: mpi-rabbitmq
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # UI admin (guest/guest)
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 20s

  redis:
    image: redis:7-alpine
    container_name: mpi-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

  catalogo:
    build: ./catalogo
    image: mpi/catalogo:v1
    container_name: mpi-catalogo
    ports:
      - "50051:50051"

  inventario:
    build: ./inventario
    image: mpi/inventario:v1
    container_name: mpi-inventario
    ports:
      - "8001:8001"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"
    depends_on:
      - redis

  pedidos:
    build: ./pedidos
    image: mpi/pedidos:v1
    container_name: mpi-pedidos
    ports:
      - "8000:8000"
    environment:
      CATALOGO_ADDR: catalogo:50051
      RABBIT_URL: amqp://guest:guest@rabbitmq:5672/
      GRPC_TIMEOUT: "0.3"
      INVENTARIO_URL: http://inventario:8001
    depends_on:
      catalogo:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      inventario:
        condition: service_started

  notificaciones:
    build: ./notificaciones
    image: mpi/notificaciones:v1
    container_name: mpi-notificaciones
    environment:
      RABBIT_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      rabbitmq:
        condition: service_healthy


  prometheus:
    image: prom/prometheus:v2.55.0
    container_name: mpi-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - inventario

  grafana:
    image: grafana/grafana:11.2.0
    container_name: mpi-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus